language: perl
sudo: false
perl:
    - "5.14"
    - "5.16"
    - "5.18"
    - "5.20"
    - "5.22"
    - "5.24"
    - "5.26"
addons:
    apt:
        packages:
            - ncbi-blast+
            - emboss
            - zip
            - gzip
            - bioperl
            - libjson-perl
            - libwww-perl
            - libtext-csv-perl
            - libfile-slurp-perl
install: 
    - "dzil authordeps --missing | cpanm"
    - "dzil listdeps --missing | cpanm"
script:
    - "bin/abricate --check"
